# ----------------------------------------------------------------------------------------------------
# Pipeline used by the azd command
# ----------------------------------------------------------------------------------------------------
name: database.net8.function.demo

infra:
    provider: bicep
    path: infra
    module: azd-main

pipeline:
    provider: github

services:
  function:
    project: src/DadaBase.Function/
    language: csharp
    host: function
