# ----------------------------------------------------------------------------------------------------
# Pipeline to deploy a Function App
# See readme file for info about variable group "DadABase.Function.Keys"
# ----------------------------------------------------------------------------------------------------
name: $(date:yyyy).$(date:MM).$(date:dd)$(rev:.r)
pool:
  vmImage: ubuntu-latest

# ----------------------------------------------------------------------------------------------------
resources:
  repositories:
  - repository: devops.library
    type: git
    name: devops.library
    ref: master

# ----------------------------------------------------------------------------------------------------
trigger:
  # since this repo has both AzDO and GHA pipelines, nothing is run automatically...
  - none
  # batch: true
  # branches:
  #   include:
  #     - main
  # paths:
  #   include:
  #     - FunctionApp
  #   exclude: 
  #     - '**/*.yml'
  #     - '**/*.yaml'
  #     - '**/*.bicep'
  #     - '**/*.md'

# ----------------------------------------------------------------------------------------------------
parameters:
  - name: deployToEnvironment
    displayName: Deploy To
    type: string
    values:
      - DEV
      - QA
      - PROD
      - MULTIPLE
    default: DEV
  - name: runGHASScan
    displayName: Run GHAS Scan
    type: boolean
    default: false
  - name: runMSDevSecOpsScan
    displayName: Run MS DevSecOps Scan
    type: boolean
    default: false

# ----------------------------------------------------------------------------------------------------
variables:
  - group: DadABase.Function.Keys
  - template: vars/var-service-connections.yml

# ----------------------------------------------------------------------------------------------------
stages:
- ${{ if ne(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
  - template: /azdo/Pipelines/pipes/function-only-pipe.yml@devops.library
    parameters:
      environments: ['${{ parameters.deployToEnvironment }}']
      singleEnvironment: 'true'
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}

- ${{ if eq(parameters.deployToEnvironment, 'DEV-QA-PROD') }}:
  - template: /azdo/Pipelines/pipes/function-only-pipe.yml@devops.library
    parameters:
      environments: ['DEV','QA','PROD']
      runMSDevSecOpsScan: ${{ parameters.runMSDevSecOpsScan }}
      runGHASScan: ${{ parameters.runGHASScan }}
