# You can also use the Swagger UI: http://localhost:7298/api/swagger/ui

@baseUrl = http://localhost:7298/api
@FunctionMasterKey = nothing

### ---------------------------------------------------------------------------
### Get a joke with plain text
GET {{baseUrl}}/RandomJoke HTTP/1.1
x-functions-key: {{FunctionMasterKey}}

### ---------------------------------------------------------------------------
### Get a joke with json formatting
GET {{baseUrl}}/RandomJokeJson HTTP/1.1
x-functions-key: {{FunctionMasterKey}}

### ---------------------------------------------------------------------------
### Search for jokes
GET {{baseUrl}}/search/cars HTTP/1.1
x-functions-key: {{FunctionMasterKey}}

### ---------------------------------------------------------------------------
### Get list of categories
GET {{baseUrl}}/categories HTTP/1.1
x-functions-key: {{FunctionMasterKey}}

### ---------------------------------------------------------------------------
### Search for jokes with text in a category
GET {{baseUrl}}/search/car/Christmas HTTP/1.1
x-functions-key: {{FunctionMasterKey}}

### ---------------------------------------------------------------------------
### Search for all jokes in a category
GET {{baseUrl}}/category/Christmas HTTP/1.1
x-functions-key: {{FunctionMasterKey}}
