# ------------------------------------------------------------------------------------------------------------------------
# GHA Workflow to deploy Azure Resources and Function App
# ------------------------------------------------------------------------------------------------------------------------
# You need to set up secrets in the GitHub Secrets Repository before running these workflows.
#   See Docs\CreateGitHubSecrets\.md for details
# ------------------------------------------------------------------------------------------------------------------------
name: 4.bicep.build.deploy.app
on: 
  workflow_dispatch:
    inputs:
      deployEnvironment:
        description: 'Environment'
        required: true
        default: 'dev' 
        type: choice
        options:
          - dev
          - qa
          - prod
      runSmokeTest:
        description: 'Run Smoke Tests'
        required: false
        default: 'true'
        type: choice
        options:
          - true
          - false
      runSecurityScan:
        description: 'Run Security Scan'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning' 
        type: choice
        options:
          - info
          - warning
          - debug 

# ------------------------------------------------------------------------------------------------------------------------
permissions:
  # these are only required for workflows in private repositories (?)
  id-token: write
  contents: write
  actions: read
  pages: write
  # required for all workflows
  security-events: write # needed for security scan to write to logs

# ------------------------------------------------------------------------------------------------------------------------
jobs:
  scan-code:
    name: Scan Source Code
    uses: ./.github/workflows/template-scan-code.yml
    secrets: inherit
    with:
      runSecurityScan: ${{ inputs.runSecurityScan == 'true' }}

# ------------------------------------------------------------------------------------------------------------------------
  build-app:
    name: Build Function App
    uses: ./.github/workflows/template-function-app-build.yml
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      rootDirectory: 'src/DadABase.Function'
      projectName: 'DadABase.Function.Net8'
      testDirectory: 'src/DadABase.Function.Tests'
      testProjectName: 'DadABase.Tests'
      testApplication: true
      listFilesAfterBuild: true

# ------------------------------------------------------------------------------------------------------------------------
  create-infra:
    name: Create Infra ${{ inputs.deployEnvironment }}
    needs: build-app
    uses: ./.github/workflows/template-create-infra.yml
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
      templatePath: './infra/Bicep/'
      templateFile: 'main.bicep'
      parameterFile: 'main.gha.bicepparam'
      parameterFileReplaceTokens: 'true'

# ------------------------------------------------------------------------------------------------------------------------
  deploy-app-demo:
    name: Deploy App
    needs: create-infra
    uses: ./.github/workflows/template-function-app-deploy.yml
    secrets: inherit
    with:
      envCode: ${{ inputs.deployEnvironment }}
